INPUT:                   | RUNTIME:                  | OUTPUT:               
  DEPTH:                 |   DEPTH:                  |   INFO:               
    NAME: depth          |     NAME: depth           |     LIST:             
    VALUE: 1             |     VALUE: 1              |       NAME: list      
  HEIGHT:                |   HEIGHT:                 |       VALUE: [raw, synapse]
    NAME: height         |     NAME: height          |     NAME: 
    VALUE: 100           |     VALUE: 100            |       NAME: name
  IMAGE:                 |   IMAGE:                  |       VALUE: synapse     
    FORMAT:              |     BLOCK:                |     PATH: 
      DEFAULT: png       |       NAME: block-size    |       NAME: path
      LIST:              |       VALUE: [512,512,1]  |       VALUE: /home/data
      - png              |     PATH:                 |     SIZE: 
      - jpg              |       NAME: path          |       NAME: dimensions
      - tif              |       VALUE: /home/data   |       VALUE: [1024,1024,1024]
      - bmp              |     SOURCE:               |       X: 
      - zip              |       DEFAULT: hdf5       |         NAME: x
      NAME: format       |       LIST:               |         VALUE: 1024
      VALUE: zip         |       - hdf5              |       Y: 
    VIEW:                |       - tilespecs         |         NAME: y
      DEFAULT: grayscale |       - mojo              |         VALUE: 1024
      LIST:              |       - regularimagestack |       Z: 
      - grayscale        |       NAME: source-type   |         NAME: z
      - colormap         |       VALUE: mojo         |         VALUE: 1024
      - rgb              |   TILE:                   |     TYPE: 
      NAME: view         |     I:                    |       NAME: data-type
      VALUE: rgb         |       NAME: i             |       VALUE: uint32   
  INFO:                  |       VALUE: [0,100]      |
    FORMAT:              |     J:                    |
      DEFAULT: json      |       NAME: j             |
      LIST:              |       VALUE: [0,100]      |
      - json             |     K:                    |
      - yaml             |       NAME: k             |
      NAME: format       |       VALUE: [0,1]        |
      VALUE: yaml        |     SI:                   |
    ID:                  |       NAME: si            |
      NAME: id           |       VALUE: 2            |
      VALUE: 0           |     SJ:                   |
  RESOLUTION:            |       NAME: sj            |
    XY:                  |       VALUE: 2            |
      NAME: resolution   |     SK:                   |
      VALUE: 1           |       NAME: sk            |
    X:                   |       VALUE: 1            |
      NAME: x-res        |   WIDTH:                  |
      VALUE: 0           |     NAME: width           |
    Y:                   |     VALUE: 100            |
      NAME: y-res        |   X:                      |
      VALUE: 0           |     NAME: x               |
    Z:                   |     VALUE: 0              |
      NAME: z-res        |   Y:                      |
      VALUE: 0           |     NAME: y               |
  WIDTH:                 |     VALUE: 0              |
    NAME: width          |   Z:                      |
    VALUE: 100           |     NAME: z               |
  X:                     |     VALUE: 0              |
    NAME: x              
    VALUE: 0             
  Y:                     
    NAME: y              
    VALUE: 0             
  Z:                     
    NAME: z              
    VALUE: 0             
                         
                         
                         
                         
                         
